# Travis CI script
language: c

os:
- linux
- osx

sudo: false

services:
- docker

env:
- BUILD_TYPE=default
- BUILD_TYPE=nodejs
- BUILD_TYPE=android
- BUILD_TYPE=cmake
- BUILD_TYPE=check_zproto
- BUILD_TYPE=check_zproject

addons:
  apt:
    packages:
    - uuid-dev
    - valgrind
    - git

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils valgrind ; fi

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh

# osx environment does not have docker
matrix:
  exclude:
  - os: osx
    env: BUILD_TYPE=check_zproto
  - os: osx
    env: BUILD_TYPE=check_zproject
